const dates = [
    { name: "Movie Night", cost: "0", time: "90" },
    { name: "Car Karaoke", cost: "5", time: "30" },
    { name: "Googly Eye Date", cost: "5", time: "30" },
    { name: "Homework Time", cost: "0", time: "60" },
    { name: "Cooking", cost: "20", time: "60" },
    { name: "Board Games", cost: "0", time: "60" },
    { name: "Walk in the Park", cost: "0", time: "30" },
    { name: "Stargazing", cost: "0", time: "60" },
    { name: "Hiking", cost: "0", time: "120" },
    { name: "Swing Dancing", cost: "10", time: "60" },
    { name: "Find a new restaurant", cost: "30", time: "90" },
    { name: "Ice Skating", cost: "15", time: "60" },
    { name: "Rollerblading/rollerskating", cost: "15", time: "60" },
    { name: "Build a fort", cost: "0", time: "60" },
    { name: "Personality Quizzes", cost: "0", time: "30" },
    { name: "Volunteer Together", cost: "0", time: "120" },
    { name: "Visit a Rest Home", cost: "0", time: "60" },
    { name: "Grocery Shopping", cost: "50", time: "60" },
    { name: "Thrifting", cost: "20", time: "60" },
    { name: "Double Date", cost: "40", time: "90" },
    { name: "Go to a play", cost: "50", time: "120" },
    { name: "Hot Chocolate", cost: "5", time: "30" },
    { name: "Sledding", cost: "0", time: "60" },
    { name: "Snowball Fight", cost: "0", time: "30" },
    { name: "Painting", cost: "20", time: "60" },
    { name: "Go to a Museum", cost: "15", time: "90" },
    { name: "Go to an Art Gallery", cost: "10", time: "60" },
    { name: "Bowling", cost: "20", time: "60" },
    { name: "Go to the Zoo", cost: "20", time: "120" },
    { name: "Read Together", cost: "0", time: "60" },
    { name: "Baking", cost: "15", time: "60" },
    { name: "Campfire", cost: "0", time: "60" },
    { name: "Yellowstone", cost: "35", time: "180" },
    { name: "Fizz Rizz", cost: "10", time: "30" },
    { name: "Snowball Fight", cost: "0", time: "30" },
    { name: "Decorate Cookies", cost: "10", time: "60" },
    { name: "Photo Shoot", cost: "0", time: "60" },
    { name: "Festival of Lights", cost: "20", time: "90" },
    { name: "Skiing/Snowboarding", cost: "60", time: "180" },
    { name: "Go to a Concert", cost: "50", time: "120" },
    { name: "Library Date", cost: "0", time: "60" },
    { name: "Call family members together", cost: "0", time: "30" },
    { name: "Find a New Hobby together", cost: "30", time: "60" },
    { name: "Roadtrip", cost: "100", time: "240" },
    { name: "Make Christmas Decorations", cost: "20", time: "60" },
    { name: "Discover New Music", cost: "0", time: "30" },
    { name: "Workout", cost: "0", time: "60" },
    { name: "Yoga", cost: "0", time: "60" },
    { name: "Write Notes for Each Other", cost: "0", time: "30" },
    { name: "Learn Spanish Together", cost: "0", time: "60" },
    { name: "Puzzle", cost: "10", time: "60" },
    { name: "Debate Things we know nothing about", cost: "0", time: "30" },
    { name: "Spa Day?", cost: "50", time: "120" },
    { name: "Have a Deep Conversation", cost: "0", time: "60" },
    { name: "Just Cuddle", cost: "0", time: "30" },
    { name: "Soccer", cost: "0", time: "60" },
    { name: "Splatter Lab", cost: "25", time: "60" },
    { name: "Crispy Cones", cost: "10", time: "30" },
    { name: "Bear World", cost: "20", time: "120" },
    { name: "Righteous Slice", cost: "15", time: "60" },
    { name: "Teton National Park", cost: "35", time: "180" },
    { name: "Temple Trip", cost: "0", time: "60" },
    { name: "Learn Pottery", cost: "30", time: "60" },
    { name: "Rexburg Planetarium", cost: "10", time: "60" },
    { name: "Idaho Falls Aquarium", cost: "15", time: "90" },
    { name: "French Fry Taste Contest", cost: "10", time: "60" },
    { name: "Walk through the greenhouses in the Benson building", cost: "0", time: "30" },
    { name: "Go to Craters of the moon park", cost: "20", time: "120" },
    { name: "Coffee Date", cost: "5", time: "30" },
    { name: "Get Chocolate", cost: "10", time: "30" },
    { name: "Buy a board game", cost: "20", time: "60" },
];
//template:
//{ name: "" },
const dateText = document.getElementById("random-date");
const dateButton = document.getElementById("button");


dateButton.addEventListener('click', () => {
    const randomNumber = Math.floor(Math.random() * dates.length);
    dateText.innerHTML = dates[randomNumber].name + " - Cost: $" + dates[randomNumber].cost + " - Time: " + dates[randomNumber].time + " minutes";
})