const dates = [
    { name: "Movie Night" },
    { name: "Car Karaoke" },
    { name: "Googly Eye Date" },
    { name: "Homework Time" },
    { name: "Cooking" },
    { name: "Board Games" },
    { name: "Walk in the Park" },
    { name: "Stargazing" },
    { name: "Hiking" },
    { name: "Swing Dancing" },
    { name: "Find a new restaurant" },
    { name: "Ice Skating" },
    { name: "Rollerblading/rollerskating" },
    { name: "Build a fort" },
    { name: "Personality Quizzes" },
    { name: "Volunteer Together" },
    { name: "Visit a Rest Home" },
    { name: "Grocery Shopping" },
    { name: "Thrifting" },
    { name: "Double Date" },
    { name: "Go to a play" },
    { name: "Hot Chocolate" },
    { name: "Sledding" },
    { name: "Snowball Fight" },
    { name: "Painting" },
    { name: "Go to a Museum" },
    { name: "Go to an Art Gallery" },
    { name: "Bowling" },
    { name: "Go to the Zoo" },
    { name: "Read Together" },
    { name: "Baking" },
    { name: "Campfire" },
    { name: "Yellowstone" },
    { name: "Fizz Rizz" },
    { name: "Snowball Fight" },
    { name: "Decorate Cookies" },
    { name: "Photo Shoot" },
    { name: "Festival of Lights" },
    { name: "Skiing/Snowboarding" },
    { name: "Go to a Concert" },
    { name: "Library Date" },
    { name: "Call family members together" },
    { name: "Find a New Hobby together" },
    { name: "Roadtrip" },
    { name: "Make Christmas Decorations" },
    { name: "Discover New Music" },
    { name: "Workout" },
    { name: "Yoga" },
    { name: "Write Notes for Each Other" },
    { name: "Learn Spanish Together" },
    { name: "Puzzle" },
    { name: "Debate Things we know nothing about" },
    { name: "Spa Day?" },
    { name: "Have a Deep Conversation" },
    { name: "Just Cuddle" },
    { name: "Soccer" },
    { name: "Splatter Lab" },
    { name: "Crispy Cones" },
    { name: "Bear World" },
    { name: "Righteous Slice" },
    { name: "Teton National Park" },
    { name: "Temple Trip" },
    { name: "Learn Pottery" },
    { name: "Rexburg Planetarium" },
    { name: "Idaho Falls Aquarium" },
    { name: "French Fry Taste Contest" },
    { name: "Walk through the greenhouses in the Benson building" },
    { name: "Go to Craters of the moon park" },
];
//template:
//{ name: "" },
const dateText = document.getElementById("random-date");
const dateButton = document.getElementById("button");


dateButton.addEventListener('click', () => {
    const randomNumber = Math.floor(Math.random() * dates.length);
    dateText.innerHTML = dates[randomNumber].name;
})